# Generated by Django 4.2.2 on 2023-10-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
